name: Deploy via FTP

on:
  push:
    branches:
      - main
      - master

jobs:
  ftp-deploy:
    name: 🚀 Deploy to Hosting
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener el código
      uses: actions/checkout@v4
      with:
        fetch-depth: 2 # Optimiza subiendo solo los archivos que cambiaron

    - name: 📂 Sincronizar archivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Cambia esto si tus archivos van en una subcarpeta (ej: public_html/, www/, htdocs/)
        # Si van en la raíz de tu usuario FTP, déjalo como ./
        server-dir: ./ 
        
        # Ignorar archivos innecesarios para que no ocupen espacio en el servidor
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/node_modules/**
          README.md
          serviceAccountKey.json
          backfill.js
